# Generated by Django 5.0.1 on 2024-01-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanagement', '0002_inbound_outbound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbound',
            old_name='date',
            new_name='date_received',
        ),
        migrations.RenameField(
            model_name='outbound',
            old_name='date',
            new_name='date_shipped',
        ),
        migrations.RenameField(
            model_name='outbound',
            old_name='customer',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='inbound',
            name='location',
            field=models.CharField(default='Storage S', max_length=255),
        ),
        migrations.AddField(
            model_name='inbound',
            name='reference',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbound',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='reference',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outbound',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
