# Generated by Django 5.0.1 on 2024-01-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanagement', '0003_rename_date_inbound_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='reference',
            field=models.CharField(default='INBOUND', max_length=255),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='reference',
            field=models.CharField(default='OUTBOUND', max_length=255),
        ),
    ]
